import ExcelJS from "exceljs";
import { saveAs } from "file-saver";
import type { CommissionLedgerEntry } from "@/src/types/commission";
import { formatCurrency } from "@/lib/utils";

const WORKSHEET_NAME = "Commission Ledger";
const HEADER_FILL = "FF1565D8";
const TOTAL_FILL = "FFFFD966";
const BRAND_NAVY = "FF001F5B";
const COLUMN_COUNT = 12;

const COLUMN_HEADERS = [
  "Sr No",
  "Date",
  "Time",
  "Transaction ID",
  "Reference",
  "Opening Balance",
  "Closing Balance",
  "Amount",
  "Credit / Debit",
  "Wallet Type",
  "Service ID",
  "Remarks",
] as const;

const MIN_COLUMN_WIDTHS: Record<number, number> = {
  1: 8,
  2: 14,
  3: 14,
  4: 38,
  5: 42,
  6: 16,
  7: 16,
  8: 14,
  9: 14,
  10: 14,
  11: 12,
  12: 28,
};

const CURRENCY_FORMAT = '"₹"#,##0.00';

const thinBorder: Partial<ExcelJS.Borders> = {
  top: { style: "thin", color: { argb: "FFCBD5E1" } },
  left: { style: "thin", color: { argb: "FFCBD5E1" } },
  bottom: { style: "thin", color: { argb: "FFCBD5E1" } },
  right: { style: "thin", color: { argb: "FFCBD5E1" } },
};

export interface CommissionExportOptions {
  generatedBy: string;
  roleLabel?: string;
}

async function loadImageAsBase64(path: string): Promise<string | null> {
  try {
    const response = await fetch(path);
    if (!response.ok) return null;
    const blob = await response.blob();
    return await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => {
        const result = String(reader.result || "");
        const base64 = result.includes(",") ? result.split(",")[1] : result;
        resolve(base64 || null);
      };
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

function applyBorder(cell: ExcelJS.Cell) {
  cell.border = thinBorder;
}

function formatFileStamp(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}_${m}_${d}`;
}

function autoFit(sheet: ExcelJS.Worksheet, headerRow: number, dataRows: number) {
  for (let col = 1; col <= COLUMN_COUNT; col += 1) {
    let maxLength = MIN_COLUMN_WIDTHS[col] ?? 14;
    for (let row = headerRow; row <= headerRow + dataRows + 1; row += 1) {
      const value = sheet.getCell(row, col).value;
      const text = value == null ? "" : String(value);
      maxLength = Math.max(maxLength, Math.min(text.length + 2, 48));
    }
    sheet.getColumn(col).width = maxLength;
  }
}

export async function exportCommissionLedgerToExcel(
  rows: CommissionLedgerEntry[],
  options: CommissionExportOptions
): Promise<void> {
  const generatedAt = new Date();
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Paytrue";
  workbook.company = "Paytrue";
  workbook.created = generatedAt;

  const sheet = workbook.addWorksheet(WORKSHEET_NAME, {
    views: [{ state: "frozen", ySplit: 7, activeCell: "A8" }],
  });

  const logoBase64 = await loadImageAsBase64("/images/paytrue-logo.png");
  if (logoBase64) {
    const imageId = workbook.addImage({
      base64: logoBase64,
      extension: "png",
    });
    sheet.addImage(imageId, {
      tl: { col: 0.2, row: 0.2 },
      ext: { width: 52, height: 52 },
    });
  }

  sheet.mergeCells(1, 2, 1, COLUMN_COUNT);
  const brandCell = sheet.getCell(1, 2);
  brandCell.value = "Paytrue";
  brandCell.font = { bold: true, size: 22, color: { argb: BRAND_NAVY } };
  brandCell.alignment = { vertical: "middle", horizontal: "left" };

  sheet.mergeCells(2, 2, 2, COLUMN_COUNT);
  const titleCell = sheet.getCell(2, 2);
  titleCell.value = "Commission Ledger Report";
  titleCell.font = { bold: true, size: 13, color: { argb: "FF1565D8" } };
  titleCell.alignment = { vertical: "middle", horizontal: "left" };

  sheet.mergeCells(3, 1, 3, COLUMN_COUNT);
  const metaCell = sheet.getCell(3, 1);
  metaCell.value = `Generated On: ${generatedAt.toLocaleString("en-IN")}  |  Generated By: ${options.generatedBy}${options.roleLabel ? ` (${options.roleLabel})` : ""}  |  Records: ${rows.length}`;
  metaCell.font = { size: 10, color: { argb: "FF475569" } };
  metaCell.alignment = { vertical: "middle", horizontal: "left" };

  sheet.mergeCells(4, 1, 4, COLUMN_COUNT);
  const noteCell = sheet.getCell(4, 1);
  noteCell.value = "Paytrue — Secure Digital Payment & Commission Wallet Statement";
  noteCell.font = { italic: true, size: 9, color: { argb: "FF64748B" } };

  sheet.getRow(1).height = 28;
  sheet.getRow(2).height = 20;
  sheet.getRow(5).height = 8;

  const headerRowIndex = 6;
  const headerRow = sheet.getRow(headerRowIndex);
  headerRow.height = 26;

  COLUMN_HEADERS.forEach((header, index) => {
    const cell = headerRow.getCell(index + 1);
    cell.value = header;
    cell.font = { bold: true, size: 11, color: { argb: "FFFFFFFF" } };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: HEADER_FILL },
    };
    cell.alignment = { horizontal: "center", vertical: "middle", wrapText: true };
    applyBorder(cell);
  });

  let totalCredit = 0;
  let totalDebit = 0;

  rows.forEach((entry, index) => {
    const row = sheet.getRow(headerRowIndex + 1 + index);
    if (entry.creditDebit === "CREDIT") totalCredit += entry.amount;
    if (entry.creditDebit === "DEBIT") totalDebit += entry.amount;

    const values: (string | number)[] = [
      index + 1,
      entry.date || "—",
      entry.time || "—",
      entry.transactionId || "—",
      entry.reference || "—",
      entry.openingBalance,
      entry.closingBalance,
      entry.amount,
      entry.creditDebit || "—",
      entry.walletType || "—",
      entry.serviceId || "—",
      entry.remarks || "—",
    ];

    values.forEach((value, colIndex) => {
      const cell = row.getCell(colIndex + 1);
      cell.value = value;
      cell.alignment = {
        horizontal: [0, 8, 9, 10].includes(colIndex) ? "center" : "left",
        vertical: "middle",
        wrapText: colIndex === 4 || colIndex === 11,
      };
      applyBorder(cell);

      if ([5, 6, 7].includes(colIndex)) {
        cell.numFmt = CURRENCY_FORMAT;
        cell.alignment = { horizontal: "right", vertical: "middle" };
      }

      if (colIndex === 8) {
        cell.font = {
          bold: true,
          color: {
            argb: entry.creditDebit === "CREDIT" ? "FF16A34A" : "FFDC2626",
          },
        };
      }

      if (index % 2 === 1) {
        cell.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: { argb: "FFF8FAFC" },
        };
      }
    });
  });

  const totalRowIndex = headerRowIndex + 1 + rows.length;
  const totalRow = sheet.getRow(totalRowIndex);
  const totalValues: (string | number)[] = [
    "",
    "",
    "",
    "",
    "TOTAL",
    "",
    "",
    totalCredit - totalDebit,
    `CR ${totalCredit.toFixed(2)} / DR ${totalDebit.toFixed(2)}`,
    "",
    "",
    "",
  ];

  totalValues.forEach((value, colIndex) => {
    const cell = totalRow.getCell(colIndex + 1);
    cell.value = value;
    cell.font = { bold: true };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: TOTAL_FILL },
    };
    cell.alignment = { horizontal: "center", vertical: "middle" };
    applyBorder(cell);
    if (colIndex === 7) {
      cell.numFmt = CURRENCY_FORMAT;
      cell.alignment = { horizontal: "right", vertical: "middle" };
    }
  });

  autoFit(sheet, headerRowIndex, rows.length + 1);

  if (rows.length > 0) {
    sheet.autoFilter = {
      from: { row: headerRowIndex, column: 1 },
      to: { row: headerRowIndex + rows.length, column: COLUMN_COUNT },
    };
  }

  const buffer = await workbook.xlsx.writeBuffer();
  saveAs(
    new Blob([buffer], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    }),
    `Paytrue_Commission_Ledger_${formatFileStamp(generatedAt)}.xlsx`
  );
}

function buildExportColumns(rows: CommissionLedgerEntry[]) {
  return rows.map((entry, index) => ({
    sr: index + 1,
    date: entry.date || "—",
    time: entry.time || "—",
    transactionId: entry.transactionId || "—",
    reference: entry.reference || "—",
    openingBalance: formatCurrency(entry.openingBalance),
    closingBalance: formatCurrency(entry.closingBalance),
    amount: formatCurrency(entry.amount),
    creditDebit: entry.creditDebit || "—",
    walletType: entry.walletType || "—",
    serviceId: entry.serviceId || "—",
    remarks: entry.remarks || "—",
  }));
}

export async function exportCommissionLedgerToPdf(
  rows: CommissionLedgerEntry[],
  options: CommissionExportOptions
): Promise<void> {
  const [{ jsPDF }, autoTableModule] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);
  const autoTable = autoTableModule.default;
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const generatedAt = new Date();
  const margin = 12;

  let logoDataUrl: string | null = null;
  try {
    const response = await fetch("/images/paytrue-logo.png");
    if (response.ok) {
      const blob = await response.blob();
      logoDataUrl = await new Promise((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(String(reader.result || null));
        reader.onerror = () => resolve(null);
        reader.readAsDataURL(blob);
      });
    }
  } catch {
    logoDataUrl = null;
  }

  if (logoDataUrl) {
    doc.addImage(logoDataUrl, "PNG", margin, 8, 12, 12);
  }

  doc.setTextColor(0, 31, 91);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Paytrue", margin + (logoDataUrl ? 16 : 0), 13);
  doc.setFontSize(11);
  doc.setTextColor(21, 101, 216);
  doc.text("Commission Ledger Report", margin + (logoDataUrl ? 16 : 0), 19);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Generated On: ${generatedAt.toLocaleString("en-IN")}  |  Generated By: ${options.generatedBy}${options.roleLabel ? ` (${options.roleLabel})` : ""}  |  Records: ${rows.length}`,
    margin,
    26
  );

  const exportRows = buildExportColumns(rows);

  autoTable(doc, {
    startY: 30,
    head: [
      [
        "Sr",
        "Date",
        "Time",
        "Transaction ID",
        "Reference",
        "Opening",
        "Closing",
        "Amount",
        "C/D",
        "Wallet",
        "Service",
        "Remarks",
      ],
    ],
    body: exportRows.map((row) => [
      row.sr,
      row.date,
      row.time,
      row.transactionId,
      row.reference,
      row.openingBalance,
      row.closingBalance,
      row.amount,
      row.creditDebit,
      row.walletType,
      row.serviceId,
      row.remarks,
    ]),
    styles: { fontSize: 7, cellPadding: 1.5, overflow: "linebreak" },
    headStyles: {
      fillColor: [21, 101, 216],
      textColor: 255,
      fontStyle: "bold",
      fontSize: 7,
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { cellWidth: 10 },
      3: { cellWidth: 32 },
      4: { cellWidth: 40 },
    },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Paytrue Confidential · Page ${i} of ${pageCount}`,
      margin,
      doc.internal.pageSize.getHeight() - 6
    );
  }

  doc.save(`Paytrue_Commission_Ledger_${formatFileStamp(generatedAt)}.pdf`);
}

export function printCommissionLedger(
  rows: CommissionLedgerEntry[],
  options: CommissionExportOptions
): void {
  const generatedAt = new Date();
  const exportRows = buildExportColumns(rows);
  const headers = [
    "Sr",
    "Date",
    "Time",
    "Transaction ID",
    "Reference",
    "Opening Balance",
    "Closing Balance",
    "Amount",
    "Credit/Debit",
    "Wallet Type",
    "Service ID",
    "Remarks",
  ];

  const win = window.open("", "_blank");
  if (!win) return;

  win.document.write(`<!DOCTYPE html>
<html>
<head>
  <title>Paytrue Commission Ledger</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: Arial, Helvetica, sans-serif; color: #0b1f3a; margin: 24px; }
    .brand { display: flex; align-items: center; gap: 12px; margin-bottom: 8px; }
    .brand img { width: 42px; height: 42px; object-fit: contain; }
    .brand h1 { margin: 0; font-size: 28px; color: #001F5B; }
    .brand h1 span { background: linear-gradient(90deg, #0A84FF, #0057D9); -webkit-background-clip: text; color: transparent; }
    .subtitle { margin: 0 0 4px; color: #1565d8; font-weight: 700; font-size: 14px; }
    .meta { color: #64748b; font-size: 12px; margin-bottom: 16px; }
    table { width: 100%; border-collapse: collapse; font-size: 11px; }
    th { background: #1565d8; color: #fff; padding: 8px 6px; text-align: left; border: 1px solid #cbd5e1; }
    td { padding: 7px 6px; border: 1px solid #e2e8f0; vertical-align: top; }
    tr:nth-child(even) td { background: #f8fafc; }
    .credit { color: #16a34a; font-weight: 700; }
    .debit { color: #dc2626; font-weight: 700; }
    .footer { margin-top: 16px; font-size: 11px; color: #94a3b8; }
    @media print {
      body { margin: 12px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="brand">
    <img src="${window.location.origin}/images/paytrue-logo.png" alt="Paytrue" />
    <div>
      <h1>Pay<span>true</span></h1>
      <p class="subtitle">Commission Ledger Report</p>
    </div>
  </div>
  <p class="meta">
    Generated On: ${generatedAt.toLocaleString("en-IN")} &nbsp;|&nbsp;
    Generated By: ${options.generatedBy}${options.roleLabel ? ` (${options.roleLabel})` : ""} &nbsp;|&nbsp;
    Records: ${rows.length}
  </p>
  <table>
    <thead>
      <tr>${headers.map((h) => `<th>${h}</th>`).join("")}</tr>
    </thead>
    <tbody>
      ${exportRows
        .map(
          (row) => `<tr>
          <td>${row.sr}</td>
          <td>${row.date}</td>
          <td>${row.time}</td>
          <td>${row.transactionId}</td>
          <td>${row.reference}</td>
          <td>${row.openingBalance}</td>
          <td>${row.closingBalance}</td>
          <td>${row.amount}</td>
          <td class="${row.creditDebit === "CREDIT" ? "credit" : row.creditDebit === "DEBIT" ? "debit" : ""}">${row.creditDebit}</td>
          <td>${row.walletType}</td>
          <td>${row.serviceId}</td>
          <td>${row.remarks}</td>
        </tr>`
        )
        .join("")}
    </tbody>
  </table>
  <p class="footer">Paytrue — Secure Digital Payment Platform. Confidential document.</p>
  <script>window.onload = function(){ window.print(); }</script>
</body>
</html>`);
  win.document.close();
}
