export const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_BASE_URL || "https://apis.paytrue.co.in/api/v1";

export const API_ENDPOINTS = {
  login: "/auth/login",
  verifyLoginOtp: "/auth/verify-login-otp",
  resendLoginOtp: "/auth/resend-login-otp",
  profile: "/auth/profile",
  users: "/users",
  wallet: "/wallet",
  walletTransfer: "/wallet/transfer",
  walletDeduct: "/wallet/deduct",
  walletTransfers: "/wallet/transfers",
  walletSummary: "/wallet/summary",
  walletLedger: "/retailer/wallet-ledger",
  walletLedgerExport: "/retailer/wallet-ledger/export",
  aepsLedger: "/retailer/aeps-ledger",
  aepsLedgerExport: "/retailer/aeps-ledger/export",
  walletAepsBalance: "/wallet/aeps/balance",
  walletCommission: "/wallet/commission",
  walletCommissionLedger: "/wallet/commission/ledger",
  walletCommissionTransferToMain: "/wallet/commission/transfer-to-main",
  fundRequests: "/fund-requests",
  myBankAccounts: "/my-bank-accounts",
  dashboardRetailer: "/dashboard/retailer",
  dashboardBusiness: "/dashboard/business",
  dashboardStats: "/dashboard/stats",
  changePassword: "/auth/change-password",
  forgotPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password",
  sendEmailVerification: "/auth/send-email-verification",
  verifyEmail: "/auth/verify-email",
  sendMobileOtp: "/auth/send-otp",
  verifyMobileOtp: "/auth/verify-otp",
  resendMobileOtp: "/auth/resend-otp",
  mpinStatus: "/retailer/mpin/status",
  mpinCreate: "/retailer/mpin/create",
  mpinChange: "/retailer/mpin/change",
  mpinVerify: "/retailer/mpin/verify",
};
