/** DMT API paths — relative to API_BASE_URL (/api/v1) */
export const DMT_ENDPOINTS = {
  remitterCheck: "/dmt/remitter/check",
  senderSearch: "/dmt/sender/search",
  remitterRegister: "/dmt/remitter/register",
  registerSender: "/dmt/sender/register",
  remitterSendOtp: "/dmt/remitter/send-otp",
  sendSenderOtp: "/dmt/sender/send-otp",
  remitterVerifyOtp: "/dmt/remitter/verify-otp",
  verifySenderOtp: "/dmt/sender/verify-otp",
  remitterEkyc: "/dmt/remitter/ekyc",
  remitterByMobile: (mobile) => `/dmt/remitter/${encodeURIComponent(mobile)}`,
  senderByMobile: (mobile) => `/dmt/sender/${encodeURIComponent(mobile)}`,
  banks: "/dmt/banks",
  beneficiaries: "/dmt/beneficiaries",
  beneficiaryVerify: (id) => `/dmt/beneficiaries/${encodeURIComponent(id)}/verify`,
  beneficiaryDelete: (id) => `/dmt/beneficiaries/${encodeURIComponent(id)}`,
  beneficiaryDeleteVerify: (id) =>
    `/dmt/beneficiaries/${encodeURIComponent(id)}/delete/verify`,
  transactionGenerateOtp: "/dmt/transaction/generate-otp",
  transactionVerifyOtp: "/dmt/transaction/verify-otp",
  transferImps: "/dmt/transfer/imps",
  transferNeft: "/dmt/transfer/neft",
  transfer: "/dmt/transfer",
  transferStatus: (reference) => `/dmt/status/${encodeURIComponent(reference)}`,
  transactions: "/dmt/transactions",
  receipt: (reference) => `/dmt/receipt/${encodeURIComponent(reference)}`,
  refund: (reference) => `/dmt/refund/${encodeURIComponent(reference)}`,
};
